# Generated by Django 4.2.7 on 2023-11-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_band_like_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='like_new',
        ),
        migrations.AddField(
            model_name='listing',
            name='like_new',
            field=models.BooleanField(default=False),
        ),
    ]
